### ISSUE TITLE
Actual publishing rate does not match filter_data_rate in param.yml

### ISSUE THREAD

**Issue by chedanix** [LORD-MicroStrain/ROS-MSCL#137]
**Describe the bug**
Actual publishing rate of `/nav/filtered_imu/data` and `/nav/odom` are twice as fast as the `filter_data_rate` in `param.yml`

**To Reproduce**
1. launch microstrain.launch
2. rostopic **hz** /nav/filtered_imu/data
3. rostopic **hz** /nav/odom
4. observe that the rate is twice as fast

**Expected behavior**
The publishing rate should match `filter_data_rate`

**Environment (please complete the following information):**
 - OS: Ubuntu 16.04
 - ROS Version: Kinetic
 - Sensor(s): 3DM-GQ7

**Modifications**
No

**Launch Parameters**
[gq7_gps_params.zip](https://github.com/LORD-MicroStrain/microstrain_inertial/files/8272768/gq7_gps_params.zip)

**Additional context**
Let me know if you can't replicate it.

**Comment by robbiefish** [comment]
Hi @chedanix

My apologies for not responding to this sooner. Thank you for bringing this to our attention. I can observe this behavior on the `ros` or `ros2` branches. This was happening because we would publish all filter messages whenever we received any filter messages. This will be fixed in #131 for ROS and #132 for ROS2.

**Comment by robbiefish** [comment]
This should have been fixed with #131 for ROS and #132 for ROS2. Please feel free to reopen if you still experience this behavior

**Comment by Acerox41** [comment]
Using 3DM-GQ7 and setting `filter_data_rate` in `params.yml` to `1000` yields to the same problem. I am using the current firmware and version of the driver.
`rostopic hz /nav/odom` results into `2000 Hz`. Interestingly the topics `/nav/status` and `/nav/dual_antenna_status` get published with `1000 Hz`.

I observed following weird behavior by using `rostopic hz /nav/odom/header`:

```
seq: 245570
stamp: 
  secs: 1701763737
  nsecs: 967000000
frame_id: "sensor_wgs84"

seq: 245571
stamp: 
  secs: 1701763737
  nsecs: 967000000
frame_id: "sensor_wgs84"

seq: 245572
stamp: 
  secs: 1701763737
  nsecs: 968000000
frame_id: "sensor_wgs84"

seq: 245573
stamp: 
  secs: 1701763737
  nsecs: 968000000
frame_id: "sensor_wgs84"

seq: 245574
stamp: 
  secs: 1701763737
  nsecs: 969000000
frame_id: "sensor_wgs84"

seq: 245575
stamp: 
  secs: 1701763737
  nsecs: 970000000
frame_id: "sensor_wgs84"

seq: 245576
stamp: 
  secs: 1701763737
  nsecs: 970000000
frame_id: "sensor_wgs84"

seq: 245577
stamp: 
  secs: 1701763737
  nsecs: 970000000
frame_id: "sensor_wgs84"

seq: 245578
stamp: 
  secs: 1701763737
  nsecs: 971000000
frame_id: "sensor_wgs84"
```
It publishes same timestamps twice (sometimes even three times) containing identical data.

Using 3DM-GV7 with 1000 Hz works completely fine.

Any advices?
