### ISSUE TITLE
undefined reference to `boost::system::detail::generic_category_instance' building with C++17

### ISSUE THREAD

**Issue by lucasw** [LORD-MicroStrain/ROS-MSCL#156]
**Describe the bug**

I think this is because mscl isn't built with C++17 (so this issue could ultimately belong to the mscl repo)

```
2022-05-22T15:14:13.2117432Z microstrain_inertial_driver_node.cpp:(.text._ZNK5boost6system14error_category12std_category10equivalentERKSt10error_codei[_ZNK5boost6system14error_category12std_category10equivalentERKSt10error_codei]+0x44): undefined reference to `boost::system::detail::generic_category_instance'
2022-05-22T15:14:13.2118740Z /usr/bin/ld: microstrain_inertial_driver_node.cpp:(.text._ZNK5boost6system14error_category12std_category10equivalentERKSt10error_codei[_ZNK5boost6system14error_category12std_category10equivalentERKSt10error_codei]+0x63): undefined reference to `boost::system::detail::generic_category_instance'
...
```

I need to build with C++17 to avoid a log4cxx 0.12 issue while building in Ubuntu 22.04, but the issue can be demonstrated in 20.04 also.

**To Reproduce**

20.04 instructions:

Use https://github.com/lucasw/microstrain_inertial/tree/cpp17

---

22.04 instructions (added before figuring out the same issue exists in 20.04

I'm building this on Ubuntu 22.04 which has boost 1.74 and g++ 11.2.0

I've removed dependenices on diagnostic_updater and roslint in https://github.com/lucasw/microstrain_inertial/tree/ubuntu2204_minimal

I also have to use C++17 to compile to avoid a log4cxx 0.12 issue (I'll see if it builds fine on 20.04 with that change also, but possibly this is a component to the issue if mscl doesn't like C++17 here)

Basic ros packages can be installed in 22.04 with apt (no ppa necessary, I may be missing a few other packages here): 

```
sudo apt install ros-* catkin
```

These repos are needed to be checked out in source to satisfy dependencies because they aren't available via apt:

```
repositories:
  geographic_info:
    type: git
    url: git@github.com:ros-geographic-info/geographic_info.git
    version: master
  mavros:
    type: git
    url: git@github.com:mavlink/mavros.git
    version: master
  microstrain_inertial:
    type: git
    url: git@github.com:lucasw/microstrain_inertial
    version: ubuntu2204_minimal
  nmea_msgs:
    type: git
    url: git@github.com:ros-drivers/nmea_msgs
    version: master
  unique_identifier:
    type: git
    url: git@github.com:ros-geographic-info/unique_identifier.git
    version: master
```

these CATKIN_IGNOREs are used to further reduce dependencies:

```
./mavros/mavros/CATKIN_IGNORE
./mavros/test_mavros/CATKIN_IGNORE
./mavros/libmavconn/CATKIN_IGNORE
./mavros/mavros_extras/CATKIN_IGNORE
./microstrain_inertial/microstrain_inertial_rqt/CATKIN_IGNORE
```

Finally build with catkin_make (same issue occurs with catkin build but catkin_tools has to be installed from source)

```
ROS_VERSION=1 catkin_make
```

I can put all of the above into a Dockerfile if there's interest but you don't have 22.04 conveniently available.

**Expected behavior**

The microstrain driver builds to completion

**Environment (please complete the following information):**
 - OS: Ubuntu 20.04 (also 22.04)
 - Architecture: [x86_64
 - ROS Version: noetic/'o'
 - Version: [e.g. 2.0.0]

**Modifications**
Did you modify the source code in any way while testing? If so, please note those modifications here.

Yes as mentioned above: https://github.com/lucasw/microstrain_inertial/tree/cpp17

**Launch Parameters**
If you have an updated `params.yml` file, please attach it to this issue.

**Additional context**
