### ISSUE TITLE
NMEA

### ISSUE THREAD

**Issue by binoy-meridian** [LORD-MicroStrain/ROS-MSCL#160]
We are connecting a lidar with the lord, the lidar need PPS input and NMEA(GPGGA, GPZDA) MESSAGE FROM GPS to  do the timestamping in the pointcloud.
So that we can get the accurate time with respect to the location captured..
Usually we give NMEA output from gps to lidar sensor.
As the NMEA is not present here in lord is there any other way to timestamp the lidar data? Though ros of lord or some other ways.?
Thanks
Meridian Geomatics

**Comment by nathanmillermicrostrain** [comment]
Hello,

What device are you using?  If it is a GQ7, you can enable RTK dongle handshaking which will output a GGA message on the AUX port. Note: this will be interlaced with a MIP message, so either the lidar will need to be able to reject the MIP message, or you could act as the middle man and strip out the NMEA and send it yourself.  Also note, NMEA output on the main port is on our list for the next GQ7 firmware release, which I don't have a hard date on, but should be around the end of summer.  

If you are using a different device, we don't have a solution currently.

Hope that helps,

Nathan

**Comment by robbiefish** [comment]
Hi @binoy-meridian, to add some more information to what @nathanmillerparker just said

If using the GQ7, you can configure the device to output a PPS signal via a GPIO line. Please note that you will need to have a wire with GPIO leads. The following config shows an example of outputting a PPS signal on GPIO line 1 which is on the main port of the GQ7. Change "gpio1" in the following config to a different number between 1-4 to use a different GPIO line.

```yaml
gpio1_feature  : 2
gpio1_behavior : 2
gpio_config : True

filter_pps_source : 1  # Ensure that you have at least GNSS antenna 1 connected to the GQ7. If you have GNSS antenna 2 connected, change this value to 2
```

In terms of the NMEA sentences, the GQ7 outputs GPGGA NMEA sentences on the aux port. If you are able to use only GPGGA sentences in conjunction with the PPS source and can connect the aux port, you can use the following config to publish the NMEA sentences to the ROS network:

```yaml
aux_port : /dev/ttyACM1  # Change this to wherever the aux port is located
rtk_dongle_enable : True
publish_nmea : True
```

However, if you need both GPGGA and GPZDA, you will need to form those messages yourself. If you configure the device to output its device timestamp, you could form NMEA sentences with the timestamp of any of the filter or GNSS messages

```yaml
use_device_timestamp : True
```
