### ISSUE TITLE
receiving different imu data after migrating to ros2-4.1.0 from ros2-4.0.0

### ISSUE THREAD

**Issue by mrzamottaghi** [LORD-MicroStrain/ROS-MSCL#338]
I have been using  version `ros2-4.0.0` and everything was looking fine. However, after upgrading this repository to the latest ros2 version, I am getting different results out of the topic `/imu/data`. To show this I attached my 3DMCV7-AR imu sensor to the table as shown in this picture 

![IMG_1168(2)](https://github.com/LORD-MicroStrain/microstrain_inertial/assets/108842070/142facd2-b980-40b4-b7b2-7d3399a6732b)

using the ros2-4.0.0 version I am getting the following result out of `/imu/data` topic 
```
header:
  stamp:
    sec: 1720224322
    nanosec: 200006693
  frame_id: imu_link
orientation:
  x: -0.005650007861061779
  y: -0.7082052530777803
  z: 0.003674360537011858
  w: 0.7059744301310432
```
However after switching to the latest ros2 version, I am getting the following result from `/imu/data`
```
header:
  stamp:
    sec: 1720224065
    nanosec: 469269517
  frame_id: imu_link
orientation:
  x: 0.002467643210590281
  y: 0.707826070436809
  z: -0.008047244426263075
  w: 0.7063366099843013
```
Why am I getting two different results  and how can I get the same result as  ros2-4.0.0 out of newer versions? (Note that this problem can  be even observed  after migrating to `ros2-4.1.0`)

 - OS: Ubuntu 22.04
 - Architecture: x86_64
 - ROS Version: humble
 - Version: ros2-4.1.0
 - Sensor(s): 3DMCV7-AR 
 - Firmware: 1.0.07
